stages:

  data_preprocessing:
    cmd: python src/data_preprocessing.py --config=params.yaml
    deps:
      - data/train
      - data/test
      - src/data_preprocessing.py


  train:
    cmd: python src/training.py --config=params.yaml

    deps:
      - data/train
      - data/test
      - src/data_preprocessing.py
      - src/training.py
      - models_saved

    params:
      - estimators.VGG16.params.input_shape
      - estimators.VGG16.params.weights
      - estimators.VGG16.params.activation
      - estimators.VGG16.params.loss
      - estimators.VGG16.params.optimizer
      - estimators.VGG16.params.metrics
      - estimators.VGG16.params.epochs

    metrics:
      - report/metrics/scores.json:
          cache: false
      - report/metrics/params.json:
          cache: false

    outs:
      - models_saved

  evaluation:
    cmd: python src/evaluation.py --config=params.yaml

    deps:
      - data/test
      - models_saved
      - src/data_preprocessing.py

    metrics:
      - report/metrics/metric.json:
          cache: false







