stages:

  train_and_evaluate:
    cmd: python src/train_and_evaluate.py --config=params.yaml
    deps:
    - data/train
    - data/test
    - src/train_and_evaluate.py
    params:
    - estimators.VGG16.params.input_shape
    - estimators.VGG16.params.weights
    metrics:
    - report/scores.json:
        cache: false
    - report/params.json:
        cache: false
    outs:
    - saved_models/


