base:
  project: pneumonia-detection
  image_size: [224, 224]
  output: 2

# data_source:
#   s3_source: data_given/winequality.csv

load_data:
  train_path: data/train
  test_path: data/test


preprocessing:

  Image_Data_Generator:

    shear_range: 0.2
    zoom_range: 0.2

  batch_size: 32
  class_mode: categorical


estimators:

  VGG16:
    params:
      input_shape:  [224, 224, 3]
      weights: imagenet
      activation: softmax
      loss: binary_crossentropy
      optimizer: adam
      metrics: accuracy
      epochs: 1


prediction:
  normal_img_path: data/test/NORMAL/IM-0011-0001-0001.jpeg
  pneumo_img_path: data/test/PNEUMONIA/person1_virus_9.jpeg



model_dir: models_saved

reports:
    model_summary_path: reports/model_summary
    params_path: reports/metrics/params.json
    scores_path: reports/metrics/scores.json

# webapp_model_dir: prediction_service/model/model.joblib